source 'https://rubygems.org'

gem 'rails', '2.3.5'
gem 'rake',  '0.8.7'
gem 'json'
gem 'rest-client', '1.6.7'
gem 'mysql', '2.9.1'
gem 'passenger', '4.0.2'
gem 'settingslogic'
gem 'mysql2', '0.2.18'
