--- 
development: 
  facility.name: Test Centre
  demographic.fields: Occupation,Home of Origin,Current District,Current Village,Current T/A,Office Phone Number,Landmark or Plot,Nationality,Home Phone Number
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004
  project.name: Billing
test: 
  facility.name: Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004
  project.name: Billing
production: 
  facility.name: Test Centre
  patient.registration.url: http://localhost:3005
  user.management.url: http://localhost:3004
  project.name: Billing
